
import { Project, User } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alex Thompson', role: 'Lead Estimator', avatar: 'https://picsum.photos/seed/user1/100/100' },
  { id: 'u2', name: 'Sarah Miller', role: 'Senior QS', avatar: 'https://picsum.photos/seed/user2/100/100' },
  { id: 'u3', name: 'David Chen', role: 'Junior QS', avatar: 'https://picsum.photos/seed/user3/100/100' },
  { id: 'admin1', name: 'James Wilson', role: 'Commercial Manager', avatar: 'https://picsum.photos/seed/admin/100/100', isAdmin: true },
];

export const MOCK_PROJECTS: Project[] = [
  { 
    id: 'p1', 
    title: 'Grand Plaza HVAC Upgrade', 
    client: 'BuildCorp', 
    assignedTo: 'u1', 
    currentStage: 'estimation', 
    status: 'active',
    updatedAt: new Date(Date.now() - 3600000 * 2), 
    value: 450000,
    mainCategory: 'Interior fit out',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Michael Scott',
    itDesignReviewer: 'Dwight Schrute',
    projectQsOwner: 'Jim Halpert',
    areaSqFt: 15000,
    levels: 3,
    notes: 'Urgent priority for Q4. Focus on chiller efficiency.',
    tasks: [
      { id: 't1', title: 'Review equipment schedule', isCompleted: true },
      { id: 't2', title: 'Obtain quotes from suppliers', isCompleted: false }
    ],
    logs: [
      { id: 'l1', userId: 'u1', message: 'Project initialized', timestamp: new Date(Date.now() - 86400000 * 2) },
      { id: 'l2', userId: 'u1', message: 'Moved from Take-off to Estimation', timestamp: new Date(Date.now() - 3600000 * 2) }
    ]
  },
  { 
    id: 'p2', 
    title: 'City Hospital Electrical Ph2', 
    client: 'HealthState', 
    assignedTo: 'u2', 
    currentStage: 'take-off', 
    status: 'active',
    updatedAt: new Date(Date.now() - 3600000 * 5), 
    value: 1200000,
    mainCategory: 'Interior + Base build',
    subCategory: 'Lab Only',
    contractType: 'Measurable',
    pricingModel: 'Open Book',
    mepDesignReviewer: 'Mike Ross',
    itDesignReviewer: 'Rachel Zane',
    projectQsOwner: 'Harvey Specter',
    areaSqFt: 50000,
    levels: 5,
    notes: 'Medical grade certification required for all switchgear.',
    tasks: [
      { id: 't3', title: 'Draft initial BoQ', isCompleted: false },
      { id: 't4', title: 'Coordinate with lead architect', isCompleted: false }
    ],
    logs: [
      { id: 'l3', userId: 'u2', message: 'Take-off started for sub-station B', timestamp: new Date(Date.now() - 3600000 * 5) }
    ]
  },
  { 
    id: 'p3', 
    title: 'BioLabs Research Center', 
    client: 'BioPharma Corp', 
    assignedTo: 'u3', 
    currentStage: 'review', 
    status: 'active',
    updatedAt: new Date(), 
    value: 850000,
    mainCategory: 'Refurbishment',
    subCategory: 'Office + Lab',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Walter White',
    itDesignReviewer: 'Jesse Pinkman',
    projectQsOwner: 'Saul Goodman',
    areaSqFt: 12500,
    levels: 1,
    notes: 'High specification laboratory ventilation requirements.',
    tasks: [
      { id: 't5', title: 'Internal peer review', isCompleted: true },
      { id: 't6', title: 'Margin adjustment approval', isCompleted: false }
    ],
    logs: [
      { id: 'l4', userId: 'u3', message: 'Estimation complete', timestamp: new Date(Date.now() - 86400000) },
      { id: 'l5', userId: 'u3', message: 'Moved to Review stage', timestamp: new Date() }
    ]
  },
  { 
    id: 'p4', 
    title: 'Skyline Office Tower', 
    client: 'Apex Properties', 
    assignedTo: 'u1', 
    currentStage: 'post-tender', 
    status: 'won',
    updatedAt: new Date(Date.now() - 86400000 * 3), 
    value: 4200000,
    mainCategory: 'Interior + Base build',
    subCategory: 'Office',
    contractType: 'Measurable',
    pricingModel: 'Open Book',
    mepDesignReviewer: 'Tony Stark',
    itDesignReviewer: 'Bruce Banner',
    projectQsOwner: 'Steve Rogers',
    areaSqFt: 180000,
    levels: 22,
    notes: 'Full MEP scope for new commercial headquarters.',
    tasks: [],
    logs: [
      { id: 'l6', userId: 'u1', message: 'Tender submitted successfully', timestamp: new Date(Date.now() - 86400000 * 10) },
      { id: 'l7', userId: 'admin1', message: 'Status changed to WON', timestamp: new Date(Date.now() - 86400000 * 3) }
    ]
  },
  { 
    id: 'p5', 
    title: 'Metro Rail MEP Sub-contracts', 
    client: 'GovTransit', 
    assignedTo: 'u2', 
    currentStage: 'tender-submission', 
    status: 'lost',
    updatedAt: new Date(Date.now() - 86400000 * 5), 
    value: 2750000,
    mainCategory: 'Refurbishment',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Marcus Wright',
    itDesignReviewer: 'Kyle Reese',
    projectQsOwner: 'John Connor',
    areaSqFt: 35000,
    levels: 2,
    notes: 'Highly competitive bid process.',
    tasks: [],
    logs: [
      { id: 'l8', userId: 'u2', message: 'Project finalized for submission', timestamp: new Date(Date.now() - 86400000 * 7) },
      { id: 'l9', userId: 'admin1', message: 'Status changed to LOST', timestamp: new Date(Date.now() - 86400000 * 5) }
    ]
  },
  { 
    id: 'p6', 
    title: 'University Library MEP', 
    client: 'UniEdu', 
    assignedTo: 'u3', 
    currentStage: 'inquiry', 
    status: 'active',
    updatedAt: new Date(), 
    value: 300000,
    mainCategory: 'Refurbishment',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Albus Dumbledore',
    itDesignReviewer: 'Minerva McGonagall',
    projectQsOwner: 'Severus Snape',
    areaSqFt: 8000,
    levels: 2,
    notes: 'Initial scope review pending.',
    tasks: [
      { id: 't7', title: 'Verify site measurements', isCompleted: false }
    ],
    logs: [
      { id: 'l10', userId: 'u3', message: 'Project inquiry received', timestamp: new Date() }
    ]
  },
  { 
    id: 'p7', 
    title: 'Data Center Cooling Ph1', 
    client: 'TechGiant', 
    assignedTo: 'u1', 
    currentStage: 'estimation', 
    status: 'active',
    updatedAt: new Date(Date.now() - 3600000 * 8), 
    value: 2500000,
    mainCategory: 'Interior + Base build',
    subCategory: 'Lab Only',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Peter Parker',
    itDesignReviewer: 'Miles Morales',
    projectQsOwner: 'Gwen Stacy',
    areaSqFt: 45000,
    levels: 1,
    notes: 'Tier 3 data center cooling requirements.',
    tasks: [
      { id: 't8', title: 'Check redundant power paths', isCompleted: false }
    ],
    logs: [
      { id: 'l11', userId: 'u1', message: 'Estimation in progress', timestamp: new Date() }
    ]
  },
  { 
    id: 'p8', 
    title: 'Luxury Hotel ELV Systems', 
    client: 'StarStay', 
    assignedTo: 'u2', 
    currentStage: 'inquiry', 
    status: 'active',
    updatedAt: new Date(), 
    value: 950000,
    mainCategory: 'Interior fit out',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Natasha Romanoff',
    itDesignReviewer: 'Clint Barton',
    projectQsOwner: 'Nick Fury',
    areaSqFt: 65000,
    levels: 12,
    notes: 'Integrated smart room controls expected.',
    tasks: [],
    logs: []
  },
  { 
    id: 'p9', 
    title: 'Shopping Mall Fire Protection', 
    client: 'RetailHub', 
    assignedTo: 'u3', 
    currentStage: 'take-off', 
    status: 'active',
    updatedAt: new Date(Date.now() - 86400000), 
    value: 600000,
    mainCategory: 'Interior fit out',
    subCategory: 'Office',
    contractType: 'Measurable',
    pricingModel: 'Open Book',
    mepDesignReviewer: 'Steve Jobs',
    itDesignReviewer: 'Bill Gates',
    projectQsOwner: 'Tim Cook',
    areaSqFt: 120000,
    levels: 4,
    notes: 'Sprinkler coverage for high-ceiling atrium.',
    tasks: [
      { id: 't9', title: 'Material count for atrium', isCompleted: false }
    ],
    logs: []
  },
  { 
    id: 'p10', 
    title: 'Airport Terminal Lighting', 
    client: 'AeroGroup', 
    assignedTo: 'u1', 
    currentStage: 'review', 
    status: 'active',
    updatedAt: new Date(Date.now() - 3600000), 
    value: 1800000,
    mainCategory: 'Interior + Base build',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Elon Musk',
    itDesignReviewer: 'Jeff Bezos',
    projectQsOwner: 'Satya Nadella',
    areaSqFt: 85000,
    levels: 2,
    notes: 'Emergency lighting system audit required.',
    tasks: [
      { id: 't10', title: 'Peer review lighting calc', isCompleted: true }
    ],
    logs: []
  },
  { 
    id: 'p11', 
    title: 'Residential Complex Plumbing', 
    client: 'HomeBuilt', 
    assignedTo: 'u2', 
    currentStage: 'estimation', 
    status: 'active',
    updatedAt: new Date(Date.now() - 86400000 * 2), 
    value: 750000,
    mainCategory: 'Refurbishment',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Clark Kent',
    itDesignReviewer: 'Lois Lane',
    projectQsOwner: 'Bruce Wayne',
    areaSqFt: 22000,
    levels: 6,
    notes: 'Retrofitting water-saving fixtures.',
    tasks: [],
    logs: []
  },
  { 
    id: 'p12', 
    title: 'Warehouse Solar PV', 
    client: 'LogisticsOne', 
    assignedTo: 'u3', 
    currentStage: 'tender-submission', 
    status: 'active',
    updatedAt: new Date(), 
    value: 1100000,
    mainCategory: 'Interior + Base build',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Arthur Curry',
    itDesignReviewer: 'Diana Prince',
    projectQsOwner: 'Barry Allen',
    areaSqFt: 200000,
    levels: 1,
    notes: 'Grid-tie-in synchronization study included.',
    tasks: [],
    logs: []
  },
  { 
    id: 'p13', 
    title: 'Tech Park Smart Building', 
    client: 'FutureSpace', 
    assignedTo: 'u1', 
    currentStage: 'post-tender', 
    status: 'active',
    updatedAt: new Date(Date.now() - 86400000 * 4), 
    value: 3500000,
    mainCategory: 'Interior fit out',
    subCategory: 'Office + Lab',
    contractType: 'Measurable',
    pricingModel: 'Open Book',
    mepDesignReviewer: 'Wanda Maximoff',
    itDesignReviewer: 'Vision',
    projectQsOwner: 'Stephen Strange',
    areaSqFt: 150000,
    levels: 8,
    notes: 'Negotiating final maintenance contract.',
    tasks: [],
    logs: []
  },
  { 
    id: 'p14', 
    title: 'Hospital Ventilation Retrofit', 
    client: 'CityHealth', 
    assignedTo: 'u2', 
    currentStage: 'post-tender', 
    status: 'won',
    updatedAt: new Date(Date.now() - 86400000 * 6), 
    value: 900000,
    mainCategory: 'Refurbishment',
    subCategory: 'Lab Only',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'TChalla',
    itDesignReviewer: 'Shuri',
    projectQsOwner: 'Okoye',
    areaSqFt: 30000,
    levels: 4,
    notes: 'HEPA filtration installation for isolation wards.',
    tasks: [],
    logs: [
      { id: 'l12', userId: 'admin1', message: 'Status changed to WON', timestamp: new Date(Date.now() - 86400000 * 6) }
    ]
  },
  { 
    id: 'p15', 
    title: 'Underground Parking Exhaust', 
    client: 'CityPlaza', 
    assignedTo: 'u3', 
    currentStage: 'estimation', 
    status: 'lost',
    updatedAt: new Date(Date.now() - 86400000 * 10), 
    value: 200000,
    mainCategory: 'Refurbishment',
    subCategory: 'Office',
    contractType: 'Lumsum',
    pricingModel: 'Close Book',
    mepDesignReviewer: 'Logan',
    itDesignReviewer: 'Charles Xavier',
    projectQsOwner: 'Erik Lehnsherr',
    areaSqFt: 12000,
    levels: 1,
    notes: 'Exhaust fan capacity upgrade.',
    tasks: [],
    logs: [
      { id: 'l13', userId: 'admin1', message: 'Status changed to LOST', timestamp: new Date(Date.now() - 86400000 * 10) }
    ]
  }
];
